### ISSUE TITLE
Multiple IMEI in configuration.json

### ISSUE THREAD

**Issue by fnolting** [lorenzo-deluca/silence-private-server#7]
Hi, is it possible to connect multiple vehicles to one silence private server running in a docker container or do we need to deploy one container for each IMEI/Vehicle?

**Comment by lorenzo-deluca** [comment]
Hello @fnolting , currently no, it's not possible but it is a functionality that can very simply be implemented.

I didn't do it initially because the project is designed to create its own local server, it can be useful if you have more scooters... 
I wouldn't recommend it for giving services to "third parties" as it is like giving the keys to your own scooter.

If you want you can contribute with a PR for this feature 👍
